language: node_js
node_js:
  - '0.10'
  - '0.11'
  - '0.12'
before_script:
 - mysql -e 'create database familynetwork-test;'
  - npm install -g gulp
script: gulp test
notifications:
  email:
    recipients:
      - ethanveres@gmail.com
    on_success: always
    on_failure: always
