language: node_js
node_js:
  - '0.10'
  - '0.11'
  - '0.12'
before_script:
  - npm install -g gulp
  - mysql -e 'create database `familynetwork_test`;'
script: gulp test
cache:
  directories:
    - node_modules
notifications:
  email:
    recipients:
      - ethanveres@gmail.com
    on_success: always
    on_failure: always
